### ISSUE TITLE
unity error when opening .vrn

### ISSUE THREAD

**Issue by jarosado0911** [stephanmg/vr-grids#8]
Hi again :)
I have run the code on different cells and it has been able to generate geometries and the .vrn file. However, when trying to access the new .vrn in Unity it produces the error attached
![image](https://user-images.githubusercontent.com/57325500/97303006-3153bb80-1830-11eb-9ff4-0cf998369597.png)

am I missing something? is there an error in the .vrn generation? Please let me know if additional information is required. I am happy to provide more.  Thanks :)

**Comment by stephanmg** [comment]
Hey @jarosado0911 thanks for reporting this.

Yes, indeed there have been some changes in the VRN format, however, this seems like an issue in the `pipeline_vr.sh`.

It's an easy fix. I will get to this hopefully on this week's Friday.

Best,
Stephan

**Comment by stephanmg** [comment]
Should be resolved, feel free to re-open if error persists. Note, you will have to pull in the vrnEnhancements branch from the c2m2/virtual-reality project.
