### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jarosado0911** [stephanmg/vr-grids#9]
I am receiving the following error when I run the pipeline code:
% Error at buffer:1 :
 % ERROR occured when trying to call 'test_import_swc_and_regularize(string, string, string, number/string, boolean, boolean):'
 % No matching overload found! Candidates are:
 %  - test_import_swc_and_regularize(string, number, string, unknown, bool, bool): type mismatch in argument 2: expected number, but given string
 %  - test_import_swc_and_regularize(string, number, string, unknown, bool, bool, number): number of parameters did not match (got 6, but needs 7).
 %  - test_import_swc_and_regularize(string): number of parameters did not match (got 6, but needs 1).
 %  - test_import_swc_and_regularize(string, bool, bool): number of parameters did not match (got 6, but needs 3).
Call Stack:
   1  buffer:1        

LUA-ERROR! Call stack:
   1  buffer:1        
 % ABORTING script parsing.
I also git pull neuro_collection, cmake .. and then make. I git pulled vr-grids as well.
I attached the .swc as a txt
[44-4.CNG_original_1d.txt](https://github.com/stephanmg/vr-grids/files/5476199/44-4.CNG_original_1d.txt)

**Comment by stephanmg** [comment]
That should in fact not happen. It seemed Travis CI was down during that time, so it did not detect the error. I will come back to this tomorrow.

**Comment by stephanmg** [comment]
I cannot reproduce your error. I build neuro_collection and ugcore with latest release, and took the `vr_pipeline.sh` script from the `experimental` branch of `vr-grids`. I invoke via `./pipeline_vr.sh -i 44-4.CNG_original -o testCell` and this works fine.

Could you provide more detail? Feel free to reopen if error persists.
